name: breeze_and_bulletin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.2
  dio: ^5.6.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: 7.6.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: any
  lottie: ^3.1.2
  retrofit: '>=4.0.0 <5.0.0'
  shimmer: ^3.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: '>=2.3.0 <4.0.0'
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  json_serializable: ^6.6.2
  mockito: ^5.4.4
  mocktail: ^1.0.4
  retrofit_generator: '>=7.0.0 <8.0.0'

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/svg/
  fonts:
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/nunito/Nunito-Regular.ttf
        - asset: lib/assets/fonts/nunito/Nunito-Medium.ttf
          weight: 400
        - asset: lib/assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/nunito/Nunito-Bold.ttf
          weight: 800

    - family: NewYorkSmall
      fonts:
        - asset: lib/assets/fonts/new_york_small/NewYorkSmall-Regular.ttf
        - asset: lib/assets/fonts/new_york_small/NewYorkSmall-Medium.ttf
          weight: 400
        - asset: lib/assets/fonts/new_york_small/NewYorkSmall-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/new_york_small/NewYorkSmall-Bold.ttf
          weight: 800

flutter_intl:
  enabled: true
  class_name: Strings
  nullsafety: